[build]
  publish = "dist/public"
  base = "client"

[[redirects]]
  from = "/api/*"
  to = "https://URL_BACKEND_ANDA.ddns.net/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200